"""Tests for the appeal generation pipeline."""

import pytest

from src.core.models import DenialExtraction, DenialReason, PatientContext
from src.core.services import AppealGenerationService
from src.integrations.ocr import MockOCRProvider

# Sample denial letter text for testing
SAMPLE_DENIAL = """
INSURANCE COMPANY NAME: Aetna Health Insurance
Date: January 5, 2025

RE: DENIAL OF PRIOR AUTHORIZATION
Member ID: AET987654321
Claim Number: CLM-2025-123456

Procedure: 64483 - Lumbar Epidural Steroid Injection
Diagnosis: M54.5 - Low back pain

REASON FOR DENIAL:
This request has been denied due to lack of medical necessity. The submitted documentation does not demonstrate that conservative treatment options have been exhausted.

You have the right to appeal within 60 days.

Medical Review Department
Aetna Health Insurance
"""


class MockLLMClient:
    """Mock LLM client for testing without API calls."""

    async def extract_denial_info(self, denial_text: str) -> DenialExtraction:
        """Return mock extraction."""
        return DenialExtraction(
            payer_name="Aetna Health Insurance",
            denial_reason=DenialReason.MEDICAL_NECESSITY,
            denial_reason_text="lack of medical necessity",
            procedure_codes=["64483"],
            diagnosis_codes=["M54.5"],
            member_id="AET987654321",
            claim_number="CLM-2025-123456",
            raw_text=denial_text,
        )

    async def generate_appeal(
        self,
        denial: DenialExtraction,
        patient_context: PatientContext | None = None,
    ) -> str:
        """Return mock appeal letter."""
        return f"""
RE: Appeal for Denial of Prior Authorization - Medical Necessity
Member ID: {denial.member_id}
Claim Number: {denial.claim_number}

Dear {denial.payer_name} Appeals Department,

I am writing to formally appeal the denial of prior authorization.

This is a test appeal letter generated by MockLLMClient.

Sincerely,
[Physician Name]
"""


@pytest.fixture
def mock_ocr():
    """Create mock OCR provider."""
    return MockOCRProvider()


@pytest.fixture
def mock_llm():
    """Create mock LLM client."""
    return MockLLMClient()


@pytest.fixture
def appeal_service(mock_ocr, mock_llm):
    """Create appeal service with mock dependencies."""
    return AppealGenerationService(
        ocr_provider=mock_ocr,
        llm_client=mock_llm,
    )


@pytest.mark.asyncio
async def test_process_denial_from_text(appeal_service):
    """Test processing denial from text input."""
    appeal = await appeal_service.process_denial_from_text(SAMPLE_DENIAL)

    assert appeal.id is not None
    assert appeal.letter_content is not None
    assert appeal.denial_extraction.payer_name == "Aetna Health Insurance"
    assert appeal.denial_extraction.denial_reason == DenialReason.MEDICAL_NECESSITY
    assert "64483" in appeal.denial_extraction.procedure_codes
    assert appeal.confidence_score > 0


@pytest.mark.asyncio
async def test_process_denial_with_patient_context(appeal_service):
    """Test processing denial with additional patient context."""
    patient_context = PatientContext(
        patient_name="Jane Doe",
        procedure_code="64483",
        procedure_description="Lumbar Epidural Steroid Injection",
        diagnosis_codes=["M54.5"],
        clinical_notes="Patient has chronic low back pain for 6 months",
        prior_treatments=["Physical therapy x 12 sessions", "NSAIDs", "Muscle relaxants"],
        treating_physician="Dr. Smith",
    )

    appeal = await appeal_service.process_denial_from_text(
        SAMPLE_DENIAL,
        patient_context,
    )

    assert appeal.denial_extraction.payer_name == "Aetna Health Insurance"
    assert appeal.letter_content is not None


@pytest.mark.asyncio
async def test_required_documents_medical_necessity(appeal_service):
    """Test that medical necessity denials include appropriate required docs."""
    appeal = await appeal_service.process_denial_from_text(SAMPLE_DENIAL)

    required_docs = appeal.required_attachments
    assert "Copy of denial letter" in required_docs
    assert "Physician letter of medical necessity" in required_docs
    assert "Relevant clinical notes and history" in required_docs


@pytest.mark.asyncio
async def test_process_denial_from_document(appeal_service):
    """Test processing denial from document bytes (uses mock OCR)."""
    # Mock document bytes
    document_bytes = b"fake pdf content"

    appeal = await appeal_service.process_denial(document_bytes)

    # Mock OCR returns the sample denial letter
    assert appeal.id is not None
    assert appeal.letter_content is not None


def test_confidence_score_calculation(appeal_service):
    """Test confidence score calculation based on extraction completeness."""
    # Full extraction should have high confidence
    full_extraction = DenialExtraction(
        payer_name="Aetna",
        denial_reason=DenialReason.MEDICAL_NECESSITY,
        denial_reason_text="Not medically necessary",
        procedure_codes=["12345"],
        diagnosis_codes=["M54.5"],
        claim_number="CLM-123",
        raw_text="test",
    )

    score = appeal_service._calculate_confidence(full_extraction)
    assert score >= 0.6  # Should be relatively high

    # Minimal extraction should have low confidence
    minimal_extraction = DenialExtraction(raw_text="test")

    score = appeal_service._calculate_confidence(minimal_extraction)
    assert score < 0.3  # Should be low
